version: '3.7'

services:
  api:
    build: api
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/database
      - PYTHONPATH=/app
    depends_on:
      - api-db
    ports:
      - "8001:8001"
  api-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5433:5432"
  soap-server:
    build: soap/spyne-soap
    volumes:
      - ./soap/spyne-soap:/app
    environment:
      - API_URL=http://api:8001
      - PYTHONPATH=/app
    depends_on:
      - api
    ports:
      - "8050:8050"
  soap-client:
    build: soap/client
    volumes:
      - ./soap/client:/app
    environment:
      - WSDL_URL=http://soap-server:8050/?wsdl
    depends_on:
      - soap-server
    ports:
      - "3000:3000"
      - "8000:8000"