# flake8:noqa
# isort:skip_file
##############################################################################
# Note: Generated by soapfish.wsdl2py at 2023-01-12 20:39:19.944176+00:00
#       Try to avoid editing it if you might need to regenerate it.
##############################################################################

from soapfish import soap, xsd

BaseHeader = xsd.ComplexType

##############################################################################
# Schemas


# http://example.com/sample.wsdl


class InitiateTransfer(xsd.ComplexType):
    pass
    INDICATOR = xsd.All
    sessionId = xsd.Element(xsd.String)
    msisdn = xsd.Element(xsd.String)
    amount = xsd.Element(xsd.String)
    language = xsd.Element(xsd.String)


class InitiateTransferResponse(xsd.ComplexType):
    pass
    INDICATOR = xsd.All
    sessionId = xsd.Element(xsd.String)
    responseCode = xsd.Element(xsd.Int)


Schema_f6600 = xsd.Schema(
    imports=[],
    includes=[],
    targetNamespace='http://example.com/sample.wsdl',
    elementFormDefault='qualified',
    simpleTypes=[],
    attributeGroups=[],
    groups=[],
    complexTypes=[],
    elements={'InitiateTransfer': xsd.Element(InitiateTransfer()), 'InitiateTransferResponse': xsd.Element(InitiateTransferResponse())},
)


##############################################################################
# Methods


InitiateTransfer_method = xsd.Method(
    soapAction='http://127.0.0.1:8050/InitiateTransfer',
    input='InitiateTransfer',
    inputPartName='parameters',
    output='InitiateTransferResponse',
    outputPartName='parameters',
    operationName='InitiateTransfer',
    style='document',
)


##############################################################################
# SOAP Service


TransServer_SERVICE = soap.Service(
    name='TransServer',
    targetNamespace='http://example.com/sample.wsdl',
    location='${scheme}://${host}/',
    schemas=[Schema_f6600],
    version=soap.SOAPVersion.SOAP11,
    methods=[InitiateTransfer_method],
)


##############################################################################
# SOAP Service Stub


class TransServerServiceStub(soap.Stub):
    SERVICE = TransServer_SERVICE
    SCHEME = 'http'
    HOST = '127.0.0.1:8050'

    def InitiateTransfer(self, InitiateTransfer, header=None):
        return self.call('InitiateTransfer', InitiateTransfer, header=header)