# flake8:noqa
# isort:skip_file
##############################################################################
# Note: Generated by soapfish.wsdl2py at 2023-01-13 22:47:57.186410+00:00
#       Try to avoid editing it if you might need to regenerate it.
##############################################################################

from soapfish import soap, xsd

BaseHeader = xsd.ComplexType


##############################################################################
# Schemas


# http://code.google.com/p/soapfish/stock.xsd


class GetStockPrice(xsd.ComplexType):
    INHERITANCE = None
    INDICATOR = xsd.Sequence
    company = xsd.Element(xsd.String, minOccurs=1)
    datetime = xsd.Element(xsd.DateTime, minOccurs=1)
    stock_list = xsd.Element(xsd.String, minOccurs=1)

    @classmethod
    def create(cls, company, datetime):
        instance = cls()
        instance.company = company
        instance.datetime = datetime
        return instance


class StockPrice(xsd.ComplexType):
    INHERITANCE = None
    INDICATOR = xsd.Sequence
    price = xsd.Element(xsd.Integer, minOccurs=1)

    @classmethod
    def create(cls, price):
        instance = cls()
        instance.price = price
        return instance


Schema_74cb6 = xsd.Schema(
    imports=[],
    includes=[],
    targetNamespace='http://code.google.com/p/soapfish/stock.xsd',
    elementFormDefault='unqualified',
    simpleTypes=[],
    attributeGroups=[],
    groups=[],
    complexTypes=[GetStockPrice, StockPrice],
    elements={'getStockPrice': xsd.Element(GetStockPrice), 'stockPrice': xsd.Element(StockPrice)},
)

##############################################################################
# Methods


GetStockPrice_method = xsd.Method(
    soapAction='http://code.google.com/p/soapfish/stock/get_stock_price',
    input='getStockPrice',
    inputPartName='body',
    output='stockPrice',
    outputPartName='body',
    operationName='GetStockPrice',
    style='document',
)

##############################################################################
# SOAP Service


ServicePort_SERVICE = soap.Service(
    name='ServicePort',
    targetNamespace='http://code.google.com/p/soapfish/stock.wsdl',
    location='${scheme}://${host}/stock',
    schemas=[Schema_74cb6],
    version=soap.SOAPVersion.SOAP11,
    methods=[GetStockPrice_method],
)


##############################################################################
# SOAP Service Stub


class ServicePortServiceStub(soap.Stub):
    SERVICE = ServicePort_SERVICE
    SCHEME = 'http'
    HOST = '127.0.0.1:8000'

    def GetStockPrice(self, getStockPrice, header=None):
        return self.call('GetStockPrice', getStockPrice, header=header)


res = ServicePortServiceStub().GetStockPrice(GetStockPrice.create('company', '2013-01-13T22:47:57.186410+00:00'))
print(res)
print(res.soap_body)
print(type(res.soap_body))
